### ISSUE TITLE
More than 2 groups for horizontal plot

### ISSUE THREAD

**Issue by simone-says** [jorvlan/raincloudplots#8]
How could i generate a plot with 9 groups that looks like the "raincloud_1_h" plot from the example code? I've seen others doing more involved figures for multiple plots, but i just need that simple one with 9 plots on shared axes lines.

**Comment by jorvlan** [comment]
Hi, that is currently not possible with the package. You could have a look here: https://github.com/jorvlan/open-visualizations where there is code on how to plot with more than 2 groups.

**Comment by kiebs** [comment]
It is still not possible to do a 2x3 raincloudplot with lines from e.g. timepoint 1 to timepoint 2 (like in figure 3.1, but with three groups instead of two), right? If no, could you tell ne how to find the code for figure17.png. Just started on Github an am a bit lost within all the files :) Thanks for this amazing package!!!
